### ISSUE TITLE
Dimitri's checklist

### ISSUE THREAD

**Issue by quassibly** [quassibly/novelty-app#163]
- [x] 1. Your `CNAME` is set up correctly
- [x] 2. Your app has a *favicon*
- [x] 3. You have correctly configured your `<meta>` tags
- [x] 4. Your pages all have an explicit `title` (> 20 characters)
- [ ] 5. Your public pages *404* and *500* are customized
- [x] 6. Your `og: image` complies with the facebook recommendation of *1200x630* pixels
